version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: architects_forum_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    command: mongod --auth

volumes:
  mongodb_data:
    driver: local
