
networks:
    architoct_network:
      name: architoct_network



services:

  mongodb:
    image: mongo:latest
    container_name: architocts_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=mvp_db
    ports:
      - "27017:27017"
    networks:
      - architoct_network
    volumes:
      - mongodb_data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    command: mongod --auth
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/forum_db --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  architoct:
    container_name: architoct_app
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      - architoct_network
    environment:
      - MONGO_URI=mongodb://admin:password123@architocts_db:27017
    ports:
      - "42069:42069"
    volumes:
      - ../logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:42069"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mongodb_data:
    driver: local
